### ISSUE TITLE
How to read the data of all-vv document

### ISSUE THREAD

**Issue by Emma123295** [medianeuroscience/emfdscore#10]
Hello, I have some problems when interpreting the data of all vice-virtue documents. The vice-virtue split is accomplished by considering the average sentiment of each foundation of each word, but I found all virtue and vice values are positive. Would you please show me how to read these values? Should I compare the size of virtue and vice value to decide if the text uses virtue or vice foundation?

**Comment by fhopp** [comment]
Hi @Emma123295 , 
yes, when you use the vice-virtue scoring option, then higher values in either a virtue or a vice column mean that the text uses a higher representation of either vices or virtues in a particular foundation. Say an article returns care.virtue .4 and care.vice .6, then you know that there is slightly more "harm" (care.vice) than "care" (care.virtue) represented.
