### ISSUE TITLE
Where is the bin/emfdscore command file?

### ISSUE THREAD

**Issue by fishfree** [medianeuroscience/emfdscore#11]
I need to edit the bin/emfdscore script file to meet my requirements. But where is it? I strictly followed the README.md to install it. My OS is Ubuntu 20.04.
Thanks in advance!

**Comment by fhopp** [comment]
If you installed it into a conda env, the bin should be at:

`/usr/local/miniconda3/envs/emfd/bin/emfdscore`

**Comment by fishfree** [comment]
@fhopp Thank you! I find it now.
