### ISSUE TITLE
Error: No module named 'sklearn.feature_extraction.stop_words'

### ISSUE THREAD

**Issue by fishfree** [medianeuroscience/emfdscore#3]
I strictly followed the installation documentation, both under Windows 10 and Ubuntu 20.04, unfortunately both failed with the bloew error:
```
root@vultr:~# emfdscore
Traceback (most recent call last):
  File "/usr/local/bin/emfdscore", line 7, in <module>
    from emfdscore.scoring import score_docs, pat_docs
  File "/usr/local/lib/python3.8/dist-packages/emfdscore/scoring.py", line 3, in <module>
    from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS
ModuleNotFoundError: No module named 'sklearn.feature_extraction.stop_words'
```
I cannot figure out why this occured.

**Comment by fhopp** [comment]
Hey there, 

from what I can tell based on your error message, you are not executing emfdscore from inside the emfd anaconda environment that should be created as part of the installation (your executable path links to "/usr/local/lib/python3.8" whereas it should execute somewhere like "/usr/local/anaconda3/envs/emfd") 

Did you run the following command (activates the venv) before running emfdscore?
$source activate emfd 

Alternatively, to make sure that the emfd env was installed, you can check your venvs via 
$conda env list

**Comment by fishfree** [comment]
@fhopp  Sorry for the mis-matched screenshot. I really used miniconda and executing emfdscore from inside the emfd anaconda environment, but the same error info.

**Comment by fishfree** [comment]
I also tried python 3.7, the same error as below:
```
(emfd) root@vultr:~/emfdscore/emfdscore# emfdscore template_input.csv all-sent.csv bow emfd all sentiment
Traceback (most recent call last):
  File "/opt/miniconda/envs/emfd/bin/emfdscore", line 7, in <module>
    from emfdscore.scoring import score_docs, pat_docs
  File "/opt/miniconda/envs/emfd/lib/python3.7/site-packages/emfdscore/scoring.py", line 3, in <module>
    from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS
ModuleNotFoundError: No module named 'sklearn.feature_extraction.stop_words'
(emfd) root@vultr:~/emfdscore/emfdscore# 

```

**Comment by fhopp** [comment]
@fishfree Apologies for the slow response. Sklearn had updated their stop-word imports. Please re-install emfdscore and try now.

**Comment by fishfree** [comment]
@fhopp It works like a charm! Thank you very much!

**Comment by JSMboli** [comment]
Hi @fhopp 
I having same issue though but I am using python 3.8.6 and the latest version of Jupyter notebook. What do you suggest I do?

**Comment by fhopp** [comment]
Hi @JSMboli ,
can you please provide some more information on what exactly the error is and also send me some more information (e.g., your operating system?). 
I just installed emfdscore via the following and it works
`conda create -n emfd python=3.8.6`
`source activate emfd`
`conda install -c conda-forge spacy`
`python -m spacy download en_core_web_sm`
`pip install https://github.com/medianeuroscience/emfdscore/archive/master.zip`

Then go to your install directory e.g., PATH:/anaconda3/envs/emfd/lib/python3.8/site-packages/emfdscore/ and test 
`emfdscore template_input.csv all-sent.csv bow emfd all sentiment`

What exact command did you use in jupyter notebook?

**Comment by JSMboli** [comment]
Hi @fhopp 
Thank you for  the prompt reply.
I am using windows 10 and this my code

from sklearn.feature_extraction.stop_words import ENGLISH_STOP_WORDS

**Comment by ArneTillmann** [comment]
Hi @JSMboli 
I looked up the folder `C:\Users\AMOR 1\anaconda3\envs\Twitter_job\Lib\site-packages\sklearn\feature_extraction` where my sklearn is stored in and found out, that the `stop_words.py` file is named `_stop_words.py`. So adding a `_` worked fine for me.

**Comment by upasanamca** [comment]
hi im using python 3.9(64 bit) and getting this error 
ModuleNotFoundError: No module named 'sklearn.feature_extraction.stop_words'. i tried to fix with above mentioned commands. but not able to solve..
Please help me to resolve this

**Comment by fhopp** [comment]
Hi @upasanamca ,
first, I'd recommend you re-install emfdscore into a clean anaconda environment following the install directions.  
If that does not fix the issue, would you please paste the entire error message that you are receiving? This will hopefully help us debug what is going on. 
Thanks!

**Comment by upasanamca** [comment]
HI @fhopp 
how to clean anaconda environment?

**Comment by fhopp** [comment]
That will depend the operating system that you are using...
Are you on Windows, Mac, or Linux?

**Comment by upasanamca** [comment]
Im using windows.

**Comment by fhopp** [comment]
Please follow this [Anaconda](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) tutorial to learn how to create environments on windows. Make sure you also follow the exact install instructions on the readme when installing the eMFD environment.

**Comment by upasanamca** [comment]
Thanks for the guidance. My issue has been resolved by using sklearn.feature_extraction.text'
