### ISSUE TITLE
What are the different applicable senarios of all probability and single probability?

### ISSUE THREAD

**Issue by fishfree** [medianeuroscience/emfdscore#8]
all vv:
![image](https://user-images.githubusercontent.com/1741341/115663422-0b3c4d80-a373-11eb-9d7d-db9084702d39.png)
single vv:
![image](https://user-images.githubusercontent.com/1741341/115663482-260ec200-a373-11eb-855a-f4891e2ddb01.png)
Apparently, values of "all vv" are correspondently larger than those of "single vv", but the variance values are not consistently larger. 
My question is : how these calculated values support interpretating moral foundations of discourses? i.e  what are the different applicable senarios of all probability and single probability? 
@jacobtfisher Hi jacob, Could you please give an example?

**Comment by jacobtfisher** [comment]
Hi there. The `single-vv` output is based on each word being assigned to an individual foundation (such as is done in previous dictionaries), and the `all_vv` output reflects each word being assigned across all foundations based on weight within each foundation. 

There are lots of reasons why you would want to use one or the other. For more information, please see the "Binary Vs. Continuous Word Weighting" section of [the manuscript](https://link.springer.com/article/10.3758/s13428-020-01433-0).

**Comment by fishfree** [comment]
@jacobtfisher Thank you!
